"""initial schema

Revision ID: ca92d1f2a2be
Revises: 
Create Date: 2026-09-07 13:26:29.976546
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'ca92d1f2a2be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('captures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('client_capture_id', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_capture_id', name='uq_capture_client')
    )
    with op.batch_alter_table('captures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_captures_user_id'), ['user_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('consumer_epoch', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_user_id'), ['user_id'], unique=False)

    op.create_table('events',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('bundle_revision', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('seq')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_events_user_seq', ['user_id', 'seq'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.String(length=120), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'endpoint', 'key_hash', name='uq_idem')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_records_user_id'), ['user_id'], unique=False)

    op.create_table('pairing_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_kind', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes_json', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    with op.batch_alter_table('pairing_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pairing_codes_user_id'), ['user_id'], unique=False)

    op.create_table('provider_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('adapter', sa.String(length=40), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.Column('prices_json', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('uploads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('mime', sa.String(length=120), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploads_user_id'), ['user_id'], unique=False)

    op.create_table('credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=False),
    sa.Column('encrypted_dek', sa.Text(), nullable=False),
    sa.Column('nonces_json', sa.JSON(), nullable=False),
    sa.Column('master_key_version', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['provider_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credentials_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credentials_user_id'), ['user_id'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('capture_id', sa.String(length=36), nullable=False),
    sa.Column('source_revision', sa.Integer(), nullable=False),
    sa.Column('bundle_revision', sa.Integer(), nullable=False),
    sa.Column('pipeline_state', sa.String(length=30), nullable=False),
    sa.Column('state_detail', sa.String(length=200), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'capture_id', name='uq_item_capture')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_items_user_state', ['user_id', 'pipeline_state'], unique=False)

    op.create_table('tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes_json', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('bundle_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('source_revision', sa.Integer(), nullable=False),
    sa.Column('manifest_key', sa.String(length=200), nullable=False),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('processing_state', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', 'revision', name='uq_bundle_rev')
    )
    with op.batch_alter_table('bundle_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bundle_revisions_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bundle_revisions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_bundle_user_item', ['user_id', 'item_id'], unique=False)

    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('relative_path', sa.String(length=300), nullable=False),
    sa.Column('mime', sa.String(length=120), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'file_id', name='uq_file_user')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_user_id'), ['user_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('source_revision', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('recipe_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', 'source_revision', 'stage', 'recipe_hash', name='uq_job')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_item_id'), ['item_id'], unique=False)
        batch_op.create_index('ix_jobs_state_not_before', ['state', 'not_before'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('bundle_revision', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('local_commit_id', sa.String(length=120), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', 'bundle_revision', 'device_id', name='uq_receipt')
    )
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipts_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_receipts_user_id'), ['user_id'], unique=False)

    op.create_table('source_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('artifacts_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', 'revision', name='uq_source_rev')
    )
    with op.batch_alter_table('source_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_revisions_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_revisions_user_id'), ['user_id'], unique=False)

    op.create_table('suppressed_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suppressed_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppressed_items_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppressed_items_user_id'), ['user_id'], unique=False)

    op.create_table('provider_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('provider_task_id', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('reserved_cost', sa.Integer(), nullable=False),
    sa.Column('actual_usage_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_operations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_operations_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_operations_user_id'), ['user_id'], unique=False)

    op.create_table('usage_ledger',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=36), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Integer(), nullable=False),
    sa.Column('price_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['provider_operations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_ledger_operation_id'), ['operation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_ledger_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_ledger_operation_id'))

    op.drop_table('usage_ledger')
    with op.batch_alter_table('provider_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_operations_user_id'))
        batch_op.drop_index(batch_op.f('ix_provider_operations_job_id'))

    op.drop_table('provider_operations')
    with op.batch_alter_table('suppressed_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppressed_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_suppressed_items_item_id'))

    op.drop_table('suppressed_items')
    with op.batch_alter_table('source_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_revisions_user_id'))
        batch_op.drop_index(batch_op.f('ix_source_revisions_item_id'))

    op.drop_table('source_revisions')
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipts_user_id'))
        batch_op.drop_index(batch_op.f('ix_receipts_item_id'))
        batch_op.drop_index(batch_op.f('ix_receipts_device_id'))

    op.drop_table('receipts')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_user_id'))
        batch_op.drop_index('ix_jobs_state_not_before')
        batch_op.drop_index(batch_op.f('ix_jobs_item_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_user_id'))
        batch_op.drop_index(batch_op.f('ix_files_item_id'))

    op.drop_table('files')
    with op.batch_alter_table('bundle_revisions', schema=None) as batch_op:
        batch_op.drop_index('ix_bundle_user_item')
        batch_op.drop_index(batch_op.f('ix_bundle_revisions_user_id'))
        batch_op.drop_index(batch_op.f('ix_bundle_revisions_item_id'))

    op.drop_table('bundle_revisions')
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_tokens_device_id'))

    op.drop_table('tokens')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index('ix_items_user_state')
        batch_op.drop_index(batch_op.f('ix_items_user_id'))

    op.drop_table('items')
    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credentials_user_id'))
        batch_op.drop_index(batch_op.f('ix_credentials_profile_id'))

    op.drop_table('credentials')
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploads_user_id'))

    op.drop_table('uploads')
    with op.batch_alter_table('provider_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_profiles_user_id'))

    op.drop_table('provider_profiles')
    with op.batch_alter_table('pairing_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pairing_codes_user_id'))

    op.drop_table('pairing_codes')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_records_user_id'))

    op.drop_table('idempotency_records')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_user_seq')
        batch_op.drop_index(batch_op.f('ix_events_user_id'))

    op.drop_table('events')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_user_id'))

    op.drop_table('devices')
    with op.batch_alter_table('captures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_captures_user_id'))

    op.drop_table('captures')
    op.drop_table('users')
    # ### end Alembic commands ###
